name: Chelsea News Monitor

on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'
  workflow_dispatch: # Manual trigger

jobs:
  monitor-chelsea-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests tweepy python-dotenv
        
    - name: Run Chelsea Monitor
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      run: python chelsea_monitor.py
      
    - name: Commit last tweet IDs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add last_tweets.json
        git diff --staged --quiet || git commit -m "Update last tweet IDs"
        git push
